apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flask-app-2024mt03611'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Keep only pods with label app=flask-app-2024mt03611
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: flask-app-2024mt03611
            action: keep
          
      # It scrapes Kubelet's cAdvisor metrics via the K8s API server proxy
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        
        # Use the in-cluster service account token and CA
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        
        # Discover all nodes
        kubernetes_sd_configs:
          - role: node
            
        relabel_configs:
          # Keep any node labels
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          
          # Set the scrape target to be the K8s API server
          - target_label: __address__
            replacement: kubernetes.default.svc:443
            
          # Rewrite the metrics path to proxy through the API server
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.*)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor